apiVersion: v1
kind: Template
metadata:
  name: xjoin-api-gateway
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      name: xjoin-api-gateway
    spec:
      envName: ${ENV_NAME}

      deployments:
        - name: api
          minReplicas: ${{NUM_REPLICAS}}
          web: true
          podSpec:
            image: ${IMAGE}:${IMAGE_TAG}
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /health
                port: metrics
                scheme: HTTP
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 5
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /health
                port: metrics
                scheme: HTTP
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 5
            env:
              - name: SCHEMA_REGISTRY_PROTOCOL
                value: ${SCHEMA_REGISTRY_PROTOCOL}
              - name: SCHEMA_REGISTRY_HOSTNAME
                value: ${SCHEMA_REGISTRY_HOSTNAME}
              - name: SCHEMA_REGISTRY_PORT
                value: ${SCHEMA_REGISTRY_PORT}

            resources:
              limits:
                cpu: ${CPU_LIMITS}
                memory: ${MEMORY_LIMITS}
              requests:
                cpu: ${CPU_REQUESTS}
                memory: ${MEMORY_REQUESTS}

parameters:
  - name: PORT
    value: '8000'
  - name: SCHEMA_REGISTRY_PROTOCOL
    value: 'http'
  - name: SCHEMA_REGISTRY_HOSTNAME
    value: 'example-apicurioregistry-kafkasql-service.test.svc'
    required: true
  - name: SCHEMA_REGISTRY_PORT
    value: '8080'
    required: true
  - name: CPU_REQUESTS
    value: 100m
  - name: CPU_LIMITS
    value: 200m
  - name: MEMORY_REQUESTS
    value: 256Mi
  - name: MEMORY_LIMITS
    value: 512Mi
  - name: NUM_REPLICAS
    value: '1'

  - name: IMAGE_TAG
    value: 'latest'
    required: true
  - name: IMAGE
    value: quay.io/ckyrouac/xjoin-api-gateway

  - description : ClowdEnvironment name
    name: ENV_NAME
    required: true
