apiVersion: v1
kind: Template
metadata:
  name: xjoin-api-gateway
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      name: xjoin-api-gateway
    spec:
      envName: ${ENV_NAME}
      testing:
        iqePlugin: xjoin
      optionalDependencies:
        - xjoin-search
        - host-inventory
      deployments:
        - name: api
          minReplicas: ${{NUM_REPLICAS}}
          webServices:
            private:
              enabled: true
          ports:
            - name: private
              protocol: TCP
              targetPort: 10000
              port: ${{PORT}}
          podSpec:
            image: ${IMAGE}:${IMAGE_TAG}
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /graphql?query=%7B__typename%7D
                port: ${{PORT}}
                scheme: HTTP
                httpHeaders:
                  - name: Content-Type
                    value: application/json
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 5
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /graphql?query=%7B__typename%7D
                port: ${{PORT}}
                scheme: HTTP
                httpHeaders:
                  - name: Content-Type
                    value: application/json
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 5
            env:
              - name: SCHEMA_REGISTRY_PROTOCOL
                value: ${SCHEMA_REGISTRY_PROTOCOL}
              - name: GRAPH_SYNC_INTERVAL
                value: "${GRAPH_SYNC_INTERVAL}"
              - name: LOG_LEVEL
                value: ${LOG_LEVEL}
              - name: REQUEST_TIMEOUT
                value: "${REQUEST_TIMEOUT}"
            resources:
              limits:
                cpu: ${CPU_LIMITS}
                memory: ${MEMORY_LIMITS}
              requests:
                cpu: ${CPU_REQUESTS}
                memory: ${MEMORY_REQUESTS}

parameters:
  - name: SCHEMA_REGISTRY_PROTOCOL
    value: 'http'
  - name: GRAPH_SYNC_INTERVAL
    value: '60000'
  - name: LOG_LEVEL
    value: 'info'
  - name: REQUEST_TIMEOUT
    value: '3000'
  - name: PORT
    value: '10000'
    required: true
  - name: CPU_REQUESTS
    value: 100m
  - name: CPU_LIMITS
    value: 200m
  - name: MEMORY_REQUESTS
    value: 256Mi
  - name: MEMORY_LIMITS
    value: 512Mi
  - name: NUM_REPLICAS
    value: '1'

  - name: IMAGE_TAG
    value: 'latest'
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/xjoin-api-gateway

  - description : ClowdEnvironment name
    name: ENV_NAME
    required: true
